[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.devnet]
viperx_agent_registry = "321hJbttyyeZ8pzisiKB93a5XdopV2N6n2gtvwrdQVRm"
viperx_perpetuals = "6Deo4a3kxfhykzK82ghBrwMY4nHE613Nz9ejb46WFcED"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
